#Various Variables
default newspaper = False
default childrenplaying = False
default seastorm = False
default promermaid = 0
default antimermaid = 0
default knocking = 0
default merjune = False
default hairpin = False
default coinpurse = False
default letter = False
default failescape = 0
default punchwindow = False
default bribeguard = False
default lookedatwindow = False
default pickedsomeone = False
default pickedsomething = False
default pickedforward = False
default pickedback = False
default sillyjune = False
default takehand = False
default traderpick = False
default amnesiapick = False
default kansaspick = False
default pr_questions = 0
default greens = 0
default fruit = 0
default fish = 0
default looked_through = False
default addfood = 0
default snoop = False
default oldladyinfo = False
default kidsinfo = False
default fishmongerinfo = False
default visitedalley = False
default bass = False
default halibut = False
default notbuyfish = False
default saiditlouder = False
default talktotext = "Talk to..."
default askedaround = "Hmm..."
default knowslocation = "Go look elsewhere."
default lookaroundtemple = "Where should I start?"
default lookaroundtemplenumber = 0
default nokeystoneattempt1 = False
default nokeystoneattempt2 = False
default askedaboutfestival = False
default muralstatuedialogue = False
default lookedatplants = False
default mural = False
default keystone = False
######################################################################
